// Regiões administrativas / bairros do Distrito Federal usados no cadastro de
// zonas de entrega — restringe a escolha a uma lista fechada (em vez de texto
// livre) pra evitar erro de digitação, que faria o bairro nunca bater com o
// que o ViaCEP retorna na hora do pedido (ver resolveDeliveryFee).
export const BRASILIA_NEIGHBORHOODS = [
  "Águas Claras",
  "Arniqueira",
  "Asa Norte",
  "Asa Sul",
  "Brazlândia",
  "Candangolândia",
  "Ceilândia",
  "Cruzeiro Novo",
  "Cruzeiro Velho",
  "Fercal",
  "Gama",
  "Guará I",
  "Guará II",
  "Itapoã",
  "Jardim Botânico",
  "Lago Norte",
  "Lago Sul",
  "Núcleo Bandeirante",
  "Octogonal",
  "Paranoá",
  "Park Way",
  "Planaltina",
  "Plano Piloto",
  "Recanto das Emas",
  "Riacho Fundo",
  "Riacho Fundo II",
  "Samambaia",
  "Santa Maria",
  "São Sebastião",
  "SCIA (Estrutural)",
  "Sobradinho",
  "Sobradinho II",
  "Sudoeste",
  "Taguatinga",
  "Varjão",
  "Vicente Pires",
] as const;
